module.exports = function (empsa) {
    return {
        empId: empsa.empId,
        name: empsa.name,
        department: empsa.department,
        jobRole: empsa.jobRole,
        workerCategory: empsa.workerCategory,
        gender: empsa.gender,
        salaryCycle: empsa.salaryCycle,
        jinengGongzi : '',
        gangweiGongzi : '',
        jichuButie : '',
        xilifei : '',
        gonglingGongzi : '',
        jibengongzi : parseFloat(empsa.jibengongzi),
        zhiwuJintie : '',
        gongliBuzhu : '',
        kaoheJiangjin : '',
        gudingJiangjin : '',
        tongxunButie : '',
        qitaJiangjin : '',
        xiaxiangBuzhu : '',
        yingyetingBuzhu : '',
        NormalOT : '',
        WeekendOT : '',
        HolidayOT : '',
        kouchu : '',
        kaohekoukuan : '',
        yingfagongzi : parseFloat(empsa.yingfagongzi),
        nianjin : parseFloat(empsa.nianjin),
        qiyeNianjin : parseFloat(empsa.qiyeNianjin),
        yanglaobaoxian : parseFloat(empsa.yanglaobaoxian),
        qiyeYanglaobaoxian : parseFloat(empsa.qiyeYanglaobaoxian),
        shiyebaoxian : parseFloat(empsa.shiyebaoxian),
        qiyeShiyebaoxian : parseFloat(empsa.qiyeShiyebaoxian),
        zhufanggongjijin : '',
        qiyeZhufanggongjijin : '',
        yiliaobaoxian : '',
        qiyeYiliaobaoxian : '',
        yingshuigongzi : parseFloat(empsa.yingshuigongzi),
        tax : parseFloat(empsa.tax),
        yicixingjiangjin : '',
        yicixingjiangjinTax : '',
        buchongyiliaobaoxian : '',
        netIncome : parseFloat(empsa.netIncome),
        daySalary : parseFloat(empsa.daySalary),
        workDays : parseFloat(empsa.workDays),
        anquanJiangli : parseFloat(empsa.anquanJiangli),
        wuweizhangJiangli : parseFloat(empsa.wuweizhangJiangli),
        OTJiangjin : parseFloat(empsa.OTJiangjin),
    }
};