module.exports = function (empId, empName) {
    return {
        empId: empId,
        name: empName,
        idCard: '',
        birthday: '',
        bankAccount: '',
        jinengGongzi: '',
        gangweiGongzi: '',
        jichuButie: '',
        xilifei: '',
        gonglingGongzi: '',
        zhiwuJintie: '',
        gongliBuzhu: '',
        kaoheJiangjin: '',
        tongxunButie: '',
        qitaJiangjin: '',
        xiaxiangBuzhu: '',
        yingyetingBuzhu: '',
        preAnnuallyIncom: '',
        nianjin: '',
        qiyeNianjin: '',
        yanglaobaoxian: '',
        shiyebaoxian: '',
        zhufanggongjijin: '',
        yiliaobaoxian: '',
        buchongyiliaobaoxian: '',
    }
}
